### ISSUE TITLE
Lost my config

### ISSUE THREAD

**Issue by bepolymathe** [zsviczian/excalibrain#127]
Hi @zsviczian 

I have a problem. My Excalibrain configuration suddenly break and I can't figure out why. I still have my old excalibrain.md file that I saved but I can't get my config back. 
Could you tell me if this is possible? I need my ontology 😿

**Comment by zsviczian** [comment]
I am so sorry... This has also happened to me, but I haven't had the time/energy to debug the root cause.
I am using obsidian sync which provides a backup for settings. If you use Obsidian sync you can open the sync settings page and restore plugin settings.

If you make backups of your vault, the ontology lives in the YOUR VAULT/.obsidian/plugins/excalibrain/data.json file. Note that .obsidian is a hidden folder, you may need to enable hidden folders on your device to view this folder.

**Comment by bepolymathe** [comment]
Hi @zsviczian 

Thanks for the tip. I've never had to restore configuration settings before with "sync". I've got it all back. 👍🏼 

I don't know if this helps but I had the impression (without being able to reproduce it) that my config broke after I mistakenly closed the main obsidian window without first closing the excalibrain pop-up window. 🤔

**Comment by zsviczian** [comment]
That could be a reason.
I did a bit of cleanup of settings save in 0.2.0, hopefully, it will do the trick, and you won't lose your ontology again.

**Comment by bepolymathe** [comment]
So far, it hasn't happened again. I'll let you know if it does. Thanks again for everything you develop.
