### ISSUE TITLE
feature or bug: 2 similars

### ISSUE THREAD

**Issue by Hansilein00726** [zsviczian/excalibrain#53]
I have 2 notes. If I write in one of notes "similar::" followed by a link, then Excalibrain shows the link and adds the label "similar". I defined similar as a friend relationship. Everything as expected. If I then similiarly write into the second note a link to the first note, then the label is "similiar, similiar". I am using Samsung S4 tablet and Android.

**Comment by zsviczian** [comment]
that is a feature... though I could/should filter the labels for identical ones. My logic is if you have multiple labels connecting two notes then you want to express multiple relationships. Based on my practice so far, I would recommend only linking from one file to the other, double linking will make your graph more rigid. e.g. if in the future you decide that a similar relationship should be a parent-child relationship by moving "similar" from the Friends list to the Children list, then the graph might not follow your changes. (I haven't thought this particular example through, but for sure I am experiencing issues with my notes imported from TheBrain, because at the time of writing the import script I created bi-directional links, and it is causing a bit of friction now, when I want to update my ontology).

I will add the filtering.

**Comment by Hansilein00726** [comment]
Oh, right! Now I understand the logic. Originally, I posed the question with a sense of irony, just to be funny. But now I really see it as a feature, too. But your thinking about a filter mechanism is also nice. Thank you very much for explaining the hidden feature, hidden at least to my eyes.😉
