### ISSUE TITLE
Pressing folder button & Obsidian graph disappears

### ISSUE THREAD

**Issue by Hansilein00726** [zsviczian/excalibrain#54]
Sometimes if I press the button to filter for folders, then the whole Excalibrain graph disappears. Maybe this happens sometimes with other buttons as well. The phenomenon appeared shortly after a dataview update. Maybe there is a relation to that.

I am using Samsung S4 tablet and Android.

**Comment by jcromwell** [comment]
I'm also having trouble seeing any graph following the latest Dataview update. I'm on Mac 12.3.

**Comment by zsviczian** [comment]
It is possible that there is a relation to the DataView update. Unfortunately, until now I haven't been able to reproduce the issue.

Is it a systemic issue, i.e. it disappears always on the same document? If yes, could you send me the file so I can try to reproduce the error with the file?

Any additional detail you can provide would be helpful. Right now I am searching completely in the dark?

One more idea, maybe could you downgrade dataview to the previous version to see if the issue is still occuring?

**Comment by jcromwell** [comment]
It happens with every document for me, regardless of the type of content.
I rolled back to Dataview 0.5.30, but that didn't fix the behavior.

**Comment by Steven-AA** [comment]
Obsidian graph disappears without pressing folder button.

Dataview 0.5.31
ExcaliDraw 1.6.33
ExcaliBrain 0.0.21
Windows 10
Graph seems need a lot of time to generate, after that it works fine.
I have to wait several minutes after opening Obsidian or switching workspace.

**Comment by zsviczian** [comment]
@Steven-AA, The wait depends on Dataview finishing the indexing. However, dataview should cache the index, thus the wait time should normally be practically zero.

@jcromwell, this seems to match your issue: https://github.com/blacksmithgu/obsidian-dataview/releases/tag/0.5.29

**Comment by zsviczian** [comment]
I upgraded to the latest dataview and finally experiencing similar issues :(

**Comment by zsviczian** [comment]
It turns out there were some breaking changes in the Dataview API. I just published ExcaliBrain 0.0.22 which should fix these issues. Please let me know if there are still other problems.

**Comment by jcromwell** [comment]
@zsviczian This has fixed the issues I was experiencing! Thank you!

**Comment by Hansilein00726** [comment]
Just a few moments ago, I installed Excalibrain and the issue seems to be gone. Thank you very much!
