### ISSUE TITLE
Canvas colour won't work

### ISSUE THREAD

**Issue by MSus4** [zsviczian/excalibrain#77]
Hi, 

Changing canvas colour won't do anything. Other colour options seem to work though.

**Comment by zsviczian** [comment]
I was able to reproduce.

**Comment by zsviczian** [comment]
seems like there is something more fundamental going on here... I am still debugging what the root cause might be. This is not the only thing that is not working. I am assuming this somehow has to do with Excalidraw-Obsidian 1.7.x for Obsidian 0.15.x popout window support.

This is the next on my todo, so I hope to sort this out in the next few days.

@MSus4, Thanks for raising this issue!

**Comment by zsviczian** [comment]
Fixed it. I want to make a few other improvements as well before releasing an update. I hope to have the update out tomorrow the latest.

**Comment by MSus4** [comment]
> Fixed it. I want to make a few other improvements as well before releasing an update. I hope to have the update out tomorrow the latest.

Sounds great, thanks!
